version: "3.8"

services:
  api01: &api
    image: tinybank-rinha-challenge:latest
    container_name: c-tinybank1.api
    hostname: api01
    build:
      context: .
      dockerfile: TinyBank/Dockerfile
    environment:
      - DB_HOSTNAME=postgres.server
      - server.port=8080
    ports:
    - "8080:8080"

    depends_on:
      -  postgres.server
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    <<: *api
    container_name: c-tinybank2.api
    hostname: api02
    ports:
    - "8081:8081"
    environment:
      - DB_HOSTNAME=postgres.server
      - server.port=8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  postgres.server:
    image: postgres:latest
    container_name: c-postgres.db
    environment:
      - POSTGRES_DB=rinhadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MAX_CONNECTIONS=200
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/rinha-db:/var/lib/postgresql/data
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres.server
    networks:
      - rinha-network
    logging:
      driver: none

networks:
  rinha-network:
    driver: bridge
