version: '3.8'

services:
  tinybank1: &api
    image: i-tinybank.api
    container_name: c-tinybank1.api
    hostname: tinybank1
    build:
      context: TinyBank
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=postgresdb
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - PORT=3000
    ports:
      - "8080:3000"  # Map container's port 3000 to host's port 8080
    depends_on:
      - postgresdb
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  tinybank2: 
    <<: *api
    container_name: c-tinybank2.api
    hostname: tinybank2
    ports:
      - "8081:3000"  # Map container's port 3000 to host's port 8081

  postgresdb:
    image: postgres:latest
    container_name: c-postgresdb
    environment:
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  rinha-network:
    driver: bridge
