version: "3.8"

services:
  tinybank1: &api
    image: lucasgarciadev22/tinybank-rinha-challenge:latest
    container_name: c-tinybank1.api
    hostname: tinybank1
    build:
      context: TinyBank
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HTTP_PORT: 8080
    depends_on:
      -  postgres.server
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  tinybank2:
    <<: *api
    container_name: c-tinybank2.api
    hostname: tinybank2
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      HTTP_PORT: 8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tinybank1
      - tinybank2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  postgres.server:
    image: postgres:latest
    container_name: c-postgres.db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinhadb
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  rinha-network:
    driver: bridge
