version: '3.4'

services:
#nginx reverse proxy service
  reverseproxy:
    container_name: nginxgateway
    restart: always
    depends_on:
      - identityserver
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "9200:9100"
       
#mongodb based database for catalog api
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

#rediscache based 'database' for basket api
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

#postgresql based database for discount api
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

#sqlserver based database for ordering api
  orderingdb:
    container_name: orderingdb
    environment:
      SA_PASSWORD: "Lucas*12345"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"

#rabbit mq services tha will be communicating ordering api with basket api trough event bus messages project
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

#pgadmin for monitoring the postgresql databases
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

#portainer for monitoring running containers
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

#catalog api data context configs, providing appsettings.json values to container context
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "9000:80"

#basket api data context configs, providing appsettings.json values to container context including cache and grpc client settings
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.api"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "9001:80"

#discount api data context configs, providing appsettings.json values to container context including postgresql settings
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"       
    depends_on:
      - discountdb
    ports:
      - "9002:80"

#ordering api data context configs, providing appsettings.json values to container context including sqlserver settings
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ConnectionStrings__OrderingConnectionString=Server=orderingdb;Database=OrderingDb;User Id=sa;Password=Lucas*12345;TrustServerCertificate=True"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
     - orderingdb
    ports:
     - "9003:80"

#ocelot api gateway for redirecting routes and managing 
  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - identityserver
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "9010:80" #global url 

#identity server auth controller for managing accesses
  identityserver:
      container_name: identityserver
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://0.0.0.0:9011    
      ports:
        - "9011:9011"