version: '3.4'

services:
#mongodb based database for catalog api
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

#rediscache based 'database' for basket api
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

#postgresql based database for discount api
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

#sqlserver based database for ordering api
  orderingdb:
    container_name: orderingdb
    environment:
        SA_PASSWORD: "lucas1234567"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

#pgadmin for monitoring the postgresql databases
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

#portainer for monitoring running containers
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

#catalog api data context configs, providing appsettings.json values to container context
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "9000:80"

#basket api data context configs, providing appsettings.json values to container context including cache and grpc client settings
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.api"
    depends_on:
      - basketdb
    ports:
      - "9001:80"

#discount api data context configs, providing appsettings.json values to container context including postgresql settings
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"       
    depends_on:
      - discountdb
    ports:
      - "9002:80"

#ordering api data context configs, providing appsettings.json values to container context including sqlserver settings
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=localhost;Database=OrderingDb;User Id=sa;Password=lucas1234567;"
    depends_on:
     - orderingdb
    ports:
     - "9003:80"
