version: "3.4"

services:
  # reverseproxy:
  #   build:
  #       context: .
  #       dockerfile: ApiGateways/nginx/nginx.Dockerfile

  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile

  # identityserver:
  #   image: ${DOCKER_REGISTRY-}identityserver
  #   build:
  #     context: .
  #     dockerfile: Infrastructure/EShopping.Identity/Dockerfile

  # APIs declarations:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  #---------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  orderingdb_data:
  elasticsearch_data:
