version: '3.8'

services:
  postgres.server:
    image: postgres:latest
    container_name: c-postgres.server
    environment:
      POSTGRES_DB: MoviesDbDev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.containers/movies-dev-db:/var/lib/postgresql/data

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Movies.API/Dockerfile
    ports:
    - "8000:8000"
    - "8001:8001"
    depends_on:
      - postgres.server
